### ISSUE TITLE
How .pth file were obtained?

### ISSUE THREAD

**Issue by mrgloom** [siriusdemon/pytorch-PCN#1]
How .pth files were obtained?

**Comment by siriusdemon** [comment]
I converted it from the original repo. I place the code in [my learning repo](https://github.com/siriusdemon/hackaway/tree/master/projects/pcn) to avoid confusion.
The [convert.py](https://github.com/siriusdemon/hackaway/blob/master/projects/pcn/convert.py) script generates the .pth file.

**Comment by siriusdemon** [comment]
I have updated README.md to add information about development repo. Thank you! @mrgloom
