### ISSUE TITLE
when real time, the speed is very slow

### ISSUE THREAD

**Issue by damvantai** [siriusdemon/pytorch-PCN#3]
why process in pytorch 3-4s / 1 frame while in c++ 31frame / 1s???

**Comment by siriusdemon** [comment]
It's sure that C++ is faster. 
Although opencv and pytorch are written in C++, there are still other overhead cost.
I recommend to use cProfiile to test it. Just for example:
```
python -m cProfile pcn.py
```
What's more, the code in this repo is converted almost line-by-line from C++ codes so it may be not very efficient.

**Comment by Edwardmark** [comment]
@siriusdemon  The demo is run on cpu, how to run it on GPU?
